
## Projects Examples

### Toss a coin
Tossing a coin can be modeled by picking a random number between `0` and `1`. If the number is `<0.5`, we call it `H` (head). If the number is `>=0.5`, we call it `T` (tail). 


::: {.callout-tip collapse="true"}

```{python}
import numpy as np

def tossacoin():
    r = np.random.rand()
    if r < 0.5:
        result = 'H'
    else:
        result = 'T'
    return result
```
:::


If we want to do it 10 times, we may use a `for` loop.


::: {.callout-tip collapse="true"}

```{python}
results = []
for i in range(10):
    results.append(tossacoin())
```
:::

The above code can be written in terms of list comprehension.

::: {.callout-tip collapse="true"}

```{python}
results = [tossacoin() for _ in range(10)]
```
Note that since the loop parameter `i` is actually not used in the loop body, we could replace it by `_` to indicate that it is not used.
:::

Now we would like to rewrite these code using `np.where()`. Consider all tossing actions simutanously. So we generate an `ndarray` of random numbers to model all tossing actions.

::: {.callout-tip collapse="true"}

```{python}
toss = np.random.rand(10)
```
:::

Then using `np.where()` to check each whether it is `H` or `T`.

::: {.callout-tip collapse="true"}

```{python}
results = np.where(toss<0.5, 'H', 'T')
```
:::

Since now `results` is an `ndarray`, we could directly use it to count the number of `H`. 

::: {.callout-tip collapse="true"}

```{python}
(results=='H').sum()
```

:::

### Random walks
Adam walks randomly along the axis. He starts from `0`. Every step he has equal possibility to go left or right. Please simulate this process.

Use `choices` to record the choice of Adam at each step. We may generate a random array where `0` represents left and `1` represents right.

Use `positions` to record the position of Adam at each step. Using `choices`, the position is `+1` if we see a `1` and the position is `-1` if we see a `0`. So the most elegent way to perform this is to 

1. Convert `choices` from `{0, 1}` to `{-1, 1}`.
2. To record the starting position, we attach `0` to the beginning of the new `choices`.
3. Apply `.cumsum()` to `choices` to get `positions`.

::: {.callout-tip collapse="true"}

```{python}
import numpy as np

step = 30
choices = np.random.randint(2, size=step)
choices = choices * 2 - 1
choices = np.concatenate(([0], choices))
positions = choices.cumsum()

import matplotlib.pyplot as plt
plt.plot(positions)
```
:::

### Many random walks
We mainly use `numpy.ndarray` to write the code in the previous example. The best part here is that it can be easily generalized to many random walks.

Still keep `choices` and `positions` in mind. Now we would like to deal with multiple people simutanously. Each row represents one person's random walk. All the formulas stay the same. We only need to update the dimension setting in the previous code.

- Update `size` in `np.random.randint`.
- Update `[0]` to `np.zeros((N, 1))` in `concatenate`.
- For `cumsum` and `concatenate`, add `axis=1` to indicate that we perform the operations along `axis 1`.
- We plot each row in the same figure. `plt.legend` is used to show the label for each line.

::: {.callout-tip collapse="true"}

```{python}
import numpy as np

step = 30
N = 3
choices = np.random.randint(2, size=(N, step))
choices = choices * 2 - 1
choices = np.concatenate((np.zeros((N, 1)), choices), axis=1)
positions = choices.cumsum(axis=1)

import matplotlib.pyplot as plt
for row in positions:
    plt.plot(row)
plt.legend([1, 2, 3])
```
:::

### Analyze `positions`
We play with the numpy array `positions` to get some information about the random walks of three generated in the previous example.

- The maximal position:

::: {.callout-tip collapse="true"}

```{python}
positions.max()
```
:::
- The maximal position for each one:

::: {.callout-tip collapse="true"}

```{python}
positions.max(axis=1)
```
:::
- The maximal position across all three for each step:


::: {.callout-tip collapse="true"}

```{python}
positions.max(axis=0)
```
:::
- Check whether anyone once got to the position 3:


::: {.callout-tip collapse="true"}

```{python}
(positions>=3).any(axis=1)
```
:::

- The number of people who once got to the position 3: 


::: {.callout-tip collapse="true"}

```{python}
(positions>=3).any(axis=1).sum()
```
:::

- Which step for each one gets to the right most position: 

::: {.callout-tip collapse="true"}

```{python}
positions.argmax(axis=1)
```

:::
